name = "featherfall/quill_rblx_lifecycles"
version = "0.1.0-alpha.1"
description = "A collection of Quill lifecycles for Roblox"
license = "MIT"
authors = ["Featherfall"]
repository = "https://github.com/featherfall-org/quill"
private = false
includes = ["lib", "lib/**", "LICENSE", "pesde.toml", "README.md"]

[target]
environment = "roblox"
lib = "lib/init.luau"
build_files = ["lib"]

[dependencies.core]
name = "featherfall/quill_core"
version = "^0.1.0-alpha.2"
index = "https://github.com/pesde-pkg/index"
