local module = require(script.Parent.Parent:FindFirstChild("howmanysmall_typed-promise@4.0.6"):FindFirstChild("typed-promise"))
export type Status  = module.Status 
export type ErrorKind  = module.ErrorKind 
export type Error  = module.Error 
export type Promise  = module.Promise 
export type TypedPromise<T...> = module.TypedPromise<T...>
export type PromiseStatic  = module.PromiseStatic 
return module