name = "featherfall/quill_logger"
version = "0.1.0-alpha.2"
description = "A tiny, context aware logger for Quill"
license = "MIT"
authors = ["Featherfall"]
repository = "https://github.com/featherfall-org/quill"
private = false
includes = ["lib", "lib/**", "LICENSE", "pesde.toml", "README.md"]

[target]
environment = "roblox"
lib = "lib/init.luau"
build_files = ["lib"]
